controller:
  type: deployment
  replicas: 1

alloy:
  stabilityLevel: experimental

  enableHttpServerPort: true
  listenAddr: 0.0.0.0
  listenPort: 12345

  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
      appProtocol: grpc
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
      appProtocol: http
