apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: flask-otel-demo:0.1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: demo-otel-config
